blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/scotlaclair/scotlaclair.github.io/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://scotlaclair.github.io/
    about: Check the documentation for guides and information
