name: 📚 Documentation
description: Report missing or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue
        
        Report missing, incorrect, or unclear documentation.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect documentation
        - Unclear documentation
        - Outdated documentation
        - Documentation enhancement
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue?
      placeholder: Which file, section, or page?
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: What's missing, incorrect, or unclear?
    validations:
      required: true

  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed Fix
      description: How should the documentation be improved?
      placeholder: What should it say instead?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or examples
